// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uklpunpsoirylrgegble.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrbHB1bnBzb2lyeWxyZ2VnYmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODA5NTQsImV4cCI6MjA2ODg1Njk1NH0.dHsBC1v-p0y3M9aHswgxLCnBZQOrfewT8n_b9oRa880";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});